# Site settings
title: Comp. Physics @ GT CSE
yourname: Spencer H. Bryngelson
email: shb@gatech.edu
description: Compuational Physics Group at Georgia Tech CSE
baseurl: ""
url: ""
exturl: "https://comp-physics.group"

# Google analytics ID: Remove or use your own!
google_analytics: UA-167467135-1
google_analytics_4: G-02KDGRRB2T
google_tag_manager: GTM-TZ9Z7HZ

# Footer info
about: >
    <a href="https://cse.gatech.edu/" target="_blank">School of CSE</a><br/>
    <a href="https://cc.gatech.edu/" target="_blank">College of Computing</a><br/>
    Georgia Tech

coordinates: >
  <br/>
  <img src='/images/logopic/logo3.png' width=90% title='This logo was designed by Sydney Bryngelson!'>

# coordinates: >
#   CODA<br/>
#   756 W Peachtree St<br/>
#   Atlanta, GA 30332

information: >
    <a href="mailto:shb@gatech.edu" target="_blank"><i class="fa fa-envelope fa-1x"></i> Email Spencer</a> <br/>
    <a href="/vacancies.html"><i class="fa fa-users fa-1x"></i> Explore openings</a> <br/>
    <a href="/aboutwebsite.html"><i class="fab fa-github fa-1x"></i> Site template</a> 



# Pages shown in navbar
nav_pages:
  - name: team
  - name: publications
  - name: research
  - name: software
  - name: teaching

include:
  - .htaccess
  - _pages

# Conversion
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false

# Markdown Processing
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false
  parse_block_html: true # default for kramdown is false. This will enable using Markdown links


plugins: 
  - jekyll-scholar
  - jekyll-seo-tag

scholar:

  last_name: Bryngelson
  first_name: [Spencer H.]

  style: shb
  locale: en

  source: /cv/
  bibliography: ref.bib
  bibliography_template: bibtemplate
  sort_by: year, month
  order: descending

  replace_strings: true
  join_strings: true

  details_dir: bibliography
  details_layout: bibtex.html
  details_link: Details

  query: "@*"

  bibliography_list_attributes:
    reversed: "reversed"

exclude:
  - Gemfile
  - Gemfile.lock
  - update_boostrap.sh
  - switch_theme.sh
  - tags
  - Rakefile
  - LICENSE
  - .DS_Store
  - jekcheck.sh
