# Site settings
title: Computational Physics @ GT
yourname: Spencer H. Bryngelson
email: shb@gatech.edu
description: Georgia Tech Computational Physics Group
baseurl: ""
url: ""
exturl: "https://comp-physics.group"

# Google analytics ID: Remove or use your own!
google_analytics: UA-167467135-1
google_analytics_4: G-02KDGRRB2T
google_tag_manager: GTM-TZ9Z7HZ

# Footer info
about: >
    Prof. Spencer H. Bryngelson<br/>
    College of Computing, <a href="https://cse.gatech.edu/" target="_blank">CSE</a><br/>
    Georgia Institute of Technology

coordinates: >
  <a href="https://codatechsquare.com/" target="_blank">S1313 CODA</a><br/>
  756 W Peachtree St<br/>
  Atlanta, GA 30332

information: >
    <a href="mailto:shb@gatech.edu" target="_blank"><i class="fa fa-envelope fa-1x"></i> Contact Spencer via email</a> <br/>
    <a href="/aboutwebsite.html"><i class="fa fa-github fa-1x"></i> Use my site as a template!</a> <br/>
    <a href="/vacancies.html"><i class="fa fa-users fa-1x"></i> Explore openings</a>


# Pages shown in navbar
nav_pages:
  - name: Team
  - name: Publications
  - name: Research
  - name: Software
  - name: Teaching
  - name: GSCS22

# - name: about
# - name: talks

include:
  - .htaccess
  - _pages

# Conversion
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false

# Markdown Processing
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false
  parse_block_html: true # default for kramdown is false. This will enable using Markdown links


plugins: 
  - jekyll-scholar

scholar:

  last_name: Bryngelson
  first_name: [Spencer H.]

  style: shb
  locale: en

  source: /cv/
  bibliography: ref.bib
  bibliography_template: bibtemplate
  sort_by: year, month
  order: descending

  replace_strings: true
  join_strings: true

  details_dir: bibliography
  details_layout: bibtex.html
  details_link: Details

  query: "@*"

  bibliography_list_attributes:
    reversed: "reversed"

exclude:
  - Gemfile
  - Gemfile.lock
  - update_boostrap.sh
  - switch_theme.sh
  - tags
  - Rakefile
  - LICENSE
  - .DS_Store
  - jekcheck.sh
